services:
  rag-service:
    build:
      context: ./rag-service
      dockerfile: dockerfile
    container_name: rag-service

    volumes:
      - ./rag-service/data:/app/data
      - ./rag-service/sentence:/app/sentence
      - ./rag-service/main.py:/app/main.py
      - ./rag-service/rag.py:/app/rag.py
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/test')"]
      interval: 5s
      timeout: 600s
      retries: 100
      start_period: 120s

  orchestrator-service: 
    build:
      context: ./orchestrator-service
      dockerfile: Dockerfile
    container_name: orchestrator-service
    ports:
      - "8001:8001"
    volumes:
      - ./orchestrator-service:/app
    environment:
      - RAG_URL=${RAG_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_KEY=${FIREBASE_SERVICE_ACCOUNT_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    depends_on:
      rag-service:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-service
    container_name: frontend
    ports:
      - "8002:5173"
    volumes:
      - ./frontend-service/src:/app/src
      - ./frontend-service/public:/app/public
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - orchestrator-service