# Config file for air: https://github.com/cosmtrek/air
root = "."
tmp_dir = "tmp"

[build]
# Command to build your Go application
cmd = "go build -o ./tmp/main ."
# The binary that will be executed
bin = "tmp/main"
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories
exclude_dir = ["tmp", "vendor"]
# Log name for the build process
log = "air_build.log"

[log]
# Show log time
time = true

[misc]
# Delete tmp folder on exit
clean_on_exit = true